import { EventEmitter } from '@angular/core';
export declare class MonthPickerComponent {
    private static readonly TAG;
    private static readonly MonthCount;
    private now;
    months: string[];
    private yearMeta;
    currentMeta: any[];
    private availableColors;
    expanded: boolean;
    expandedChange: EventEmitter<boolean>;
    currentYear: number;
    currentYearChange: EventEmitter<number>;
    prevYearBtnTap: EventEmitter<{}>;
    nextYearBtnTap: EventEmitter<{}>;
    select: EventEmitter<string>;
    deselect: EventEmitter<string>;
    tabindex: number;
    monthsPerRow: number;
    colors: string[];
    locales: string | string[];
    dateOptions: any;
    expandable: boolean;
    prevYearAvailable: boolean;
    nextYearAvailable: boolean;
    useAvailableMonths: boolean;
    closeBtnIcon: string;
    prevYearBtnIcon: string;
    nextYearBtnIcon: string;
    maxSelectableItems: number;
    minSelectableItems: number;
    minYear: number;
    maxYear: number;
    ngOnInit(): void;
    private setYearMeta(year);
    private createYearMeta(year);
    selectMonth(year: number, month: number): void;
    isMonthAvailable(year: number, month: number): boolean;
    isDateInBounds(year: number, month: number): boolean;
    isMonthInBounds(month: number): boolean;
    isYearInBounds(year: number): boolean;
    private getYearMeta(year);
    private iterateMonthMetas(cb);
    getSelectedDates(): string[];
    private setMonthBackgroundColor(year, month);
    private getMonthBackgroundColor();
    deselectMonth(year: number, month: number): void;
    isMonthSelected(year: number, month: number): boolean;
    private clearMonthBackgroundColor(year, month);
    deselectAllMonths(): void;
    addAvailableMonth(year: number, month: number): void;
    removeAvailableMonth(year: number, month: number): void;
    removeAllAvailableMonths(): void;
    onPrevYearTap(): void;
    onNextYearTap(): void;
    private onCloseBtnTap();
    private notifySelect(date);
    private notifyDeselect(date);
    isCurrentMonth(year: number, month: number): boolean;
    getMonth(year: number, month: number): any;
}
